version: '3.8'

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
    volumes:
      - C:/Repos/projects/poc-opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml

    command: ["--config=/etc/otel-collector-config.yaml"]